on:
  pull_request:
    types: [opened, synchronize]
jobs:
  evaluator_job:
    name: Evaluator Job
    runs-on: ubuntu-18.04
    services:
      mongodb:
        image: mongo
        ports:
          - "27017:27017"
        options: -v ${{ github.workspace }}:/github/workspace
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
        with:	
          node-version: '12'
      - name: Static code analysis step
        uses: betrybe/eslint-linter-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Evaluator step
        id: evaluator
        uses: betrybe/jest-evaluator-action@fix-puppeteer-dep
        with:
          repository-test-name: 'betrybe/sd-0x-project-webchat-tests'
          repository-test-branch: 'main'
          npm-start: true
        env:
          DB_URL: mongodb://mongodb:27017/webchat
          DB_NAME: webchat
      - name: Store evaluation step
        uses: betrybe/store-evaluation-action@v2
        with:
          evaluation-data: ${{ steps.evaluator.outputs.result }}
          environment: production
          pr-number: ${{ github.event.number }}
